const rawRuleOrder = [
    // GENERATED CONTENT
    "content",
    null,
    // POSITION AND LAYOUT
    "z-index",
    "position",
    "top",
    "bottom",
    "left",
    "right",
    "float",
    "clear",
    null,
    // DISPLAY AND VISIBILITY
    "display",
    "flex",
    "grid",
    "justify-content",
    "align-items",
    "align-self",
    "gap",
    null,
    "opacity",
    "transform",
    null,
    // CLIPPING
    "overflow",
    "clip",
    null,
    // ANIMATION
    "animation",
    "transition",
    null,
    // BOX MODEL (FROM OUTSIDE IN)
    "margin",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "margin-inline",
    "margin-block",
    null,
    "box-shadow",
    "border",
    "border-radius",
    "box-sizing",
    null,
    "min-width",
    "min-height",
    "width",
    "height",
    "max-width",
    "max-height",
    null,
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
    "padding-inline",
    "padding-block",
    null,
    // BACKGROUND
    "background",
    "cursor",
    null,
    // TYPOGRAPHY
    "font",
    "font-family",
    "font-feature-settings",
    "font-kerning",
    "font-language-override",
    "font-optical-sizing",
    "font-palette",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-style",
    "font-synthesis-position",
    "font-synthesis-small-caps",
    "font-synthesis-style",
    "font-synthesis-weight",
    "font-variant-alternates",
    "font-variant-caps",
    "font-variant-east-asian",
    "font-variant-emoji",
    "font-variant-ligatures",
    "font-variant-numeric",
    "font-variant-position",
    "font-variation-settings",
    "font-weight",
    "text",
    "line-height",
    "word-spacing",
    "color",
];

module.exports = {
    rawRuleOrder,
};
